### PR TITLE
fix to reuters ads

### PR DESCRIPTION
**Pull request by greysonevins**
for dhowe/AdNauseam/issues/1107

### CODE REVIEW

**Comment by cqx931** [comment]
Is there any reason that you added these three rules? Aren't they already covered in easylist?
```
reuters.*#@#iframe[id^="google_ads_iframe"]
reuters.*#@#div[id^="google_ads_iframe_"]
reuters.*##div[id^="google_ads_iframe_"]
```

**Comment by greysonevins** [comment]
@cqx931 for some reason the filters coming from easy list are only blocking and not picking up the ads. So I had to allow the block rules in order to try it again with adn filters.

**Comment by dhowe** [comment]
> @cqx931 for some reason the filters coming from easy list are only blocking and not picking up the ads. So I had to allow the block rules in order to try it again with adn filters.

This doesn't really make sense to me -- @cqx931 can we check this, and if its happening, figure out why?

**Comment by greysonevins** [comment]
@dhowe @cqx931 I'm not sure why either, but in my tests of the site--this was the only way to collect the ads. Please test it:

```
reuters.*#@#iframe[id^="google_ads_iframe"]
reuters.*#@#div[id^="google_ads_iframe_"]
reuters.*##div[id^="google_ads_iframe_"]
```

**Comment by cqx931** [comment]
Please refer to my comment in https://github.com/dhowe/AdNauseam/issues/1107

**Pull request merged**
